### ISSUE TITLE
mvn package

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#1]
compilation instructions? i'm trying to use mvn package but it fails with the following error:

[ERROR] Failed to execute goal on project MobPlugin: Could not resolve dependencies for project cn.nukkit:MobPlugin:jar:0.0.2-SNAPSHOT: Could not find artifact cn.nukkit:nukkit:jar:1.0-SNAPSHOT

I've also built Nukkit, so how can I use the Nukkit repo to correct this error, if possible?

Reported From Discord.
LucidVillain666

**Comment by augesrob** [comment]
Ill Provide releases for anyone who has issues with this issue.
https://github.com/Nukkit-coders/mob-plugin/releases

**Comment by PetteriM1** [comment]
Fixed
