### ISSUE TITLE
Mobs spawn inside the wall sometimes

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/mob-plugin#17]

**Comment by augesrob** [comment]
can you share a copy of your config.yml?

**Comment by PetteriM1** [comment]
# general settings
entities:
  mob-ai: true
  auto-spawn-tick: 200
  worlds-spawn-disabled: 

# max spawn settings
max-spawns:
  bat: 0
  blaze: 0
  cave-spider: 0
  chicken: 2
  cow: 2
  creeper: 0
  donkey: 0
  enderman: 0
  ghast: 0
  horse: 0
  iron-golem: 0
  mooshroom: 2
  mule: 0
  ocelot: 2
  pig: 2
  pig-zombie: 0
  rabbit: 2
  silverfish: 0
  sheep: 2
  skeleton: 2
  skeleton-horse: 0
  snow-golem: 0
  spider: 2
  squid: 2
  witch: 0
  wolf: 2
  zombie: 2
  zombie-horse: 0
  zombie-villager: 0

**Comment by augesrob** [comment]
Try changing value of everything to 1And test it.

**Comment by PetteriM1** [comment]
Still sometimes mobs spawn inside the wall
