### ISSUE TITLE
Mobs/Animals Walk Throu Doors

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#18]
### Issue Description

Write a short description about the issue

### Steps to Reproduce the Issue

1. Spawn a mob in close area with double door.
2. Grab a food they like (Horse) hold wheat
3. They noclip through the doors.

### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10

**Comment by PetteriM1** [comment]
[https://github.com/NukkitX/Nukkit/pull/198](https://github.com/NukkitX/Nukkit/pull/198)
