### ISSUE TITLE
Animals Follow After Food Dropped

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#19]
### Issue Description

Write a short description about the issue

### Steps to Reproduce the Issue

1. Get a wheat for a horse to follow you.
2. Drop or discard the wheat.
3. The horse will follow you non-stop like your holding it.

### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10

**Comment by augesrob** [comment]
Punching them seems to stop the following.

**Comment by Spitz4478** [comment]
I think I know what's causing this, but I'm not decided on the best fix... 

In WalkingEntity.checkTarget(), the code inside "if (!(target instanceof EntityCreature) || !this.targetOption((EntityCreature) target, this.distanceSquared(target)))" is triggered when the player removes the food item from their hand. But nothing in that chunk of code tells the entity to reference another target if the player no longer has food in-hand.

To put that another way, the WalkingEntity would change its target reference if there's another player nearby with food, for example. But if no other valid target is found, the original player entity remains referenced in this.target. And in the next if chunk in checkTarget(), the function immediately returns, only after checking that the target reference is an EntityCreature, is alive and is not closed.

**Comment by Spitz4478** [comment]
Ok, I think I've figured out the easiest solution without doing any major refactoring within `WalkingEntity.checkTarget()`

Change this line: 'if (this.target instanceof EntityCreature && !((EntityCreature) this.target).closed && ((EntityCreature) this.target).isAlive()) {

To this: `if (this.target instanceof EntityCreature && !((EntityCreature) this.target).closed && ((EntityCreature) this.target).isAlive() && this.targetOption((EntityCreature) this.target, this.distanceSquared(this.target))) {`

That way if the player remains referenced in this.target after the previous for loop, but doesn't meet the targetOption() criteria (e.g. has no food in his hand), then method can continue on to assign a random vector as the new target for the entity.
