### ISSUE TITLE
Spiders are killing me and they are invisible

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#2]
### Issue Description

Spiders are killing me and they are invisible

### Steps to Reproduce the Issue

1. In survival
2. Walking around until something attacks me that you cant see
3. When you die in chat it says a spider killed <username>

### OS and Versions

* Nukkit Version: 1.2.5

*Client: Windows10

**Comment by augesrob** [comment]
Seemed to fix this issue. Set no higher than 1.

`entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: 

max-spawns:
  bat: 1
  blaze: 1
  cave-spider: 1
  chicken: 1
  cow: 1
  creeper: 1
  donkey: 1
  enderman: 1
  ghast: 1
  horse: 1
  iron-golem: 1
  mooshroom: 1
  mule: 1
  ocelot: 1
  pig: 1
  pig-zombie: 1
  rabbit: 1
  silverfish: 1
  sheep: 1
  skeleton: 1
  skeleton-horse: 1
  snow-golem: 1
  spider: 1
  squid: 1
  wolf: 1
  witch: 1
  zombie: 1
  zombie-horse: 1
  zombie-villager: 1`

**Comment by PetteriM1** [comment]
Exactly spider can kill you if it is on roof of building you are inside.
