### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#21]
Use command
/removemobs
/removeall

Says in the game: 
No command given. Usage /mob spawn <mob_name> <opt:player_name>

Does not remove the mobs from the world

Might wanna add-on to prevent entire world removal.
/removemob entity <Wolf>and etc

**Comment by augesrob** [comment]
Found a fix:
Use alt command
/mob removeall

**Comment by augesrob** [comment]
https://github.com/Nukkit-coders/mob-plugin/commit/a8efdb5360e58110c00b090029bc0995cba7c904

@PetteriM1 If you want to redo this to work better later you can. I just made a quick fix.

**Comment by augesrob** [comment]
After the last push we have new error

`[CRITICAL] Unhandled exception executing command 'mob spawn' in mob spawn: java.lang.ArrayIndexOutOfBoundsException: 1
03.12 13:14:42 [Server] INFO at de.kniffo80.mobplugin.MobPlugin.onCommand(MobPlugin.java:111)
03.12 13:14:42 [Server] INFO at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
03.12 13:14:42 [Server] INFO at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.dispatchCommand(Server.java:645)
03.12 13:14:42 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:2546)
03.12 13:14:42 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1257)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.Network.processPackets(Network.java:178)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:160)
03.12 13:14:42 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1985)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
03.12 13:14:42 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:76)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.tick(Server.java:998)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:801)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.start(Server.java:780)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.<init>(Server.java:471)
03.12 13:14:42 [Server] INFO at cn.nukkit.Nukkit.main(Nukkit.java:99)
03.12 13:14:42 [Server] INFO GK13:14:42 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 1
03.12 13:14:42 [Server] INFO at de.kniffo80.mobplugin.MobPlugin.onCommand(MobPlugin.java:111)
03.12 13:14:42 [Server] INFO at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
03.12 13:14:42 [Server] INFO at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.dispatchCommand(Server.java:645)
03.12 13:14:42 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:2546)
03.12 13:14:42 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1257)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.Network.processPackets(Network.java:178)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.Network.processBatch(Network.java:160)
03.12 13:14:42 [Server] INFO at cn.nukkit.Player.handleDataPacket(Player.java:1985)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
03.12 13:14:42 [Server] INFO at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
03.12 13:14:42 [Server] INFO at cn.nukkit.network.Network.processInterfaces(Network.java:76)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.tick(Server.java:998)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.tickProcessor(Server.java:801)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.start(Server.java:780)
03.12 13:14:42 [Server] INFO at cn.nukkit.Server.<init>(Server.java:471)
03.12 13:14:42 [Server] INFO at cn.nukkit.Nukkit.main(Nukkit.java:99)`

**Comment by PetteriM1** [comment]
Because you can't just edit them in plugin.yml

**Comment by PetteriM1** [comment]
Exactly same
https://github.com/Nukkit-coders/mob-plugin/issues/13
