### ISSUE TITLE
The prohibition of the designated world is not effective.

### ISSUE THREAD

**Issue by 2871409536** [Nukkit-coders/mob-plugin#27]
worlds-spawn-disabled: "world"
What if I want to ban more than one world?

**Comment by PetteriM1** [comment]
Try worlds-spawn-disabled: "world1,world2,world3"

**Comment by 2871409536** [comment]
Still not, there is no effect. The forbidden world will still be generated!
worlds-spawn-disabled: "world,zy"

**Comment by PetteriM1** [comment]
For me it works

**Comment by 2871409536** [comment]
Can it be done by instruction?

**Comment by PetteriM1** [comment]
What do you mean?

**Comment by 2871409536** [comment]
正在使用发音
Can the forbidden world be added by instructions?

**Comment by 2871409536** [comment]
Can the forbidden world be added by instructions?
