### ISSUE TITLE
Biogenetic error

### ISSUE THREAD

**Issue by 2871409536** [Nukkit-coders/mob-plugin#29]
I just need pigs, but I found it made pigs, bats, wolves!

entities:
  mob-ai: true
  auto-spawn-tick: 10
  worlds-spawn-disabled: "world,zy"

max-spawns:
  bat: 0
  blaze: 0
  cave-spider: 0
  chicken: 0
  cow: 0
  creeper: 0
  donkey: 0
  enderman: 0
  ghast: 0
  horse: 0
  iron-golem: 0
  mooshroom: 0
  mule: 0
  ocelot: 0
  pig: 1
  pig-zombie: 0
  rabbit: 0
  silverfish: 0
  sheep: 0
  skeleton: 0
  skeleton-horse: 0
  snow-golem: 0
  spider: 0
  squid: 0
  witch: 0
  wolf: 0
  zombie: 0
  zombie-horse: 0
  zombie-villager: 0

**Comment by PetteriM1** [comment]
First your auto-spawn-tick setting is very low, it causes lot of load to server. I recommend to put it something about 100-500.
Then restart server, do /mob removeall and see if it still spawns other animals.

**Comment by 2871409536** [comment]
Thank you. I hope you can do it all the time!
