### ISSUE TITLE
Cows not dropping leather.

### ISSUE THREAD

**Issue by jacklollz2** [Nukkit-coders/mob-plugin#37]
### Issue Description

Cows will not drop leather when killed.

### Steps to Reproduce the Issue
1. Spawn cow.
2. Kill cow.

### Nukkit Version and Client Version
* Nukkit Version: 1.2.9 #3​7 Jan 24, 2018 4:35 PM https://ci.potestas.xyz/job/NukkitX/job/master/
* Client: Windows 10 Edition

#### Config.yml
Tried many configurations.

**Comment by PetteriM1** [comment]
I cant reproduce this issue. What Mob Plugin version you use?

**Comment by jacklollz2** [comment]
Fixed, it was an issue on my end preventing the entity.
