### ISSUE TITLE
config.yml is empty by default

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/mob-plugin#4]

**Comment by augesrob** [comment]
You need to add the folder and config yourself for now. Ill automate the process soon
plugins/MobPlugin/config.yml
Create Folder MobPlugin
Add Config.yml into that folder

https://github.com/Nukkit-coders/mob-plugin/releases/download/0.0.2-SNAPSHOT-FIX/config.yml

**Comment by PetteriM1** [comment]
I'm making fix for this, check pull request soon.

**Comment by augesrob** [comment]
Sent you invite to become an admin of https://github.com/Nukkit-coders/mob-plugin/invitations
