### ISSUE TITLE
Can't hit mobs

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/mob-plugin#46]

**Comment by magicus** [comment]
This seems to be due to a recent change in NukkitX. I have confirmed that it does not work with the latest master of NukkitX, but it *does* work (with the identical mob-plugin) when I checked out 8b1ea9edbed9a11d900288fe5cdb79e31b164f03 (from 7 days ago). Something has happened since then.

**Comment by magicus** [comment]
By bisection I've concluded that the offending changeset is 572ca929cbe47e16e884c81016f631457057ad0e. Propably the problematic code is:
```
 +                                    if (this.level.getGameRules().getBoolean("pvp"))
 +                                        entityDamageByEntityEvent.setCancelled();
 +
```

**Comment by magicus** [comment]
See https://github.com/NukkitX/Nukkit/issues/104

**Comment by PetteriM1** [comment]
Fixed by Nukkit
