### ISSUE TITLE
Nukkit Bug or Mob-Plugin Bug?

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#49]
6.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] --------- Server stopped responding --------- (63.743s)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] Please report this to nukkit:
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY]  - https://github.com/NukkitX/Nukkit/issues/new
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] ---------------- Main thread ----------------
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] Current Thread: main
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	PID: 1 | Suspended: false | Native: false | State: RUNNABLE
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	Stack:
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.getBlocksAround(BaseEntity.java:208)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.checkBlockCollision(BaseEntity.java:224)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.entityBaseTick(BaseEntity.java:279)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		de.kniffo80.mobplugin.entities.animal.WalkingAnimal.entityBaseTick(WalkingAnimal.java:49)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		de.kniffo80.mobplugin.entities.animal.WalkingAnimal.onUpdate(WalkingAnimal.java:83)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		cn.nukkit.level.Level.doTick(Level.java:754)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		cn.nukkit.Server.checkTickUpdates(Server.java:989)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		cn.nukkit.Server.tick(Server.java:1075)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		cn.nukkit.Server.tickProcessor(Server.java:838)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		cn.nukkit.Server.start(Server.java:815)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		cn.nukkit.Server.<init>(Server.java:498)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		cn.nukkit.Nukkit.main(Nukkit.java:102)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] ---------------- All threads ----------------
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] Current Thread: threadDeathWatcher-3-1
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	PID: 78 | Suspended: false | Native: false | State: TIMED_WAITING
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	Stack:
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.lang.Thread.sleep(Native Method)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] ------------------------------
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] Current Thread: Timer-1
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	PID: 74 | Suspended: false | Native: false | State: TIMED_WAITING
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	Stack:
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.lang.Object.wait(Native Method)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.TimerThread.mainLoop(Timer.java:552)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.TimerThread.run(Timer.java:505)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] ------------------------------
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] Current Thread: Nukkit Asynchronous Task Handler #40
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	PID: 73 | Suspended: false | Native: false | State: WAITING
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	Stack:
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		sun.misc.Unsafe.park(Native Method)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] ------------------------------
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] Current Thread: Nukkit Asynchronous Task Handler #39
06.02 08:34:31 [Server] INFO DK
06.02 08:34:31 [Server] INFO GK08:34:31 [EMERGENCY] 	PID: 72 | Suspended: false | Native: false | State: WAITING

**Comment by PetteriM1** [comment]
When this happened?

**Comment by augesrob** [comment]
No one was on server when it occurred.

**Comment by PetteriM1** [comment]
Maybe fixed in last commit, reopen this if still hapens
