### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by LagHD** [Nukkit-coders/mob-plugin#52]
### Issue Description
You should give the wither abilities to attack by shooting those wither skull projectiles
And give the ender dragon some attack methods too it would be great and helpful, thanks!

**Comment by LagHD** [comment]
& Also mobs can't be attacked with renamed swords

**Comment by PikyCZ** [comment]
@LagHD  Wither attack with wither skull projectile in NovaMobsX  and 2issue(renamed sword) this is nukkit bug or you have bad code

**Comment by LagHD** [comment]
Okay thanks - can u send me latest jar for it?
