### ISSUE TITLE
the plugin violently crashes the server when ran in conjunction with Luckperms.

### ISSUE THREAD

**Issue by AlekEagleYT** [Nukkit-coders/mob-plugin#54]
### Issue Description

The plugin will violently crash the server when ran in conjunction with Luckperms.

### Steps to Reproduce the Issue
1. Run Luckperms with this plugin

### Nukkit Version and Client Version

* Nukkit Version: 1.2.10
* Client: server won't run long enough for clients to join it crashes immediately after mob plugin enables with Luckperms enabped

#### Config.yml
```

Put config here

```
### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by PetteriM1** [comment]
Mob plugin version? What NukkitX build? Any errors? You are sure it is Mob plugin's problem?
