### ISSUE TITLE
No Hostile Mobs Spawning

### ISSUE THREAD

**Issue by Kurt6** [Nukkit-coders/mob-plugin#58]
Only passive mobs are spawning

I have tried every setting of difficulty and trying to turn off passive mobs, but only passive ones are spawning and I cant get hostile mobs to spawn.

Write a short description about the issue

### Steps to Reproduce the Issue
1. install the plugin
2. set every value in the config to 1
3. set server to hard or Normal difficulty
4. Try to see if hostile mobs spawn.

### Nukkit Version and Client Version
This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.5 for Minecraft: PE v1.2.10 (protocol version 201)
Link to Build: [Link](https://ci.nukkitx.com/job/NukkitX/job/master/109/)

* Client: MCPE 1.2.10

#### Config.yml
https://pastebin.com/huSnhdYp

### Crashdump, Backtrace or Other Files
No Crashes or Errors in console

**Comment by PetteriM1** [comment]
And time is night?

**Comment by Kurt6** [comment]
Yes, the time is set to night.

**Comment by PetteriM1** [comment]
I can't confirm this. For me it works like it should.
