### ISSUE TITLE
Spiders stop attacking

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/mob-plugin#59]
### Issue Description

Spiders sometimes stop attacking when you hit them.

### Steps to Reproduce the Issue

1. Find wild spider at night.
2. Give it attack to you.
3. Hit the spider.

### Nukkit Version and Client Version

* Nukkit Version: 1.2.10
* Client: Windows 10

#### Config.yml
```
Any config with spider autospawn enabled
```
### Crashdump, Backtrace or Other Files

```
none
```

@zzz1999 This maybe caused by your route finding commit

**Comment by zzz1999** [comment]
Is in day?

**Comment by PetteriM1** [comment]
@zzz1999 On night.
