### ISSUE TITLE
Pathfinder bug

### ISSUE THREAD

**Issue by Creeperface01** [Nukkit-coders/mob-plugin#64]
### Issue Description

PathFinder can't find the path through 1 block width corridor and also sometimes entities get stuck at corners

### Steps to Reproduce the Issue
Build for example spiral corridor and let entity find you

### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10

#### Config.yml
```

Put config here

```
### Crashdump, Backtrace or Other Files

```
<!--- Copy and paste your backtrace here... -->
```

**Comment by zzz1999** [comment]
I can't understand your mean. Can you take a picture to show this appearance?

**Comment by Creeperface01** [comment]
I'll record it, BTW its probably caused because nodes coordinates are floored and maybe they should be in the center of block so + 0.5
