### ISSUE TITLE
NullPointerException when a player Dies and left the server

### ISSUE THREAD

**Issue by Marfjeh** [Nukkit-coders/mob-plugin#67]
### Issue Description
When the player Dies and left the server, the mob for example zombie is still trying to track the player and causes a NullPointerException.

### Steps to Reproduce the Issue
1. Spawn a mob, for example, a zombie.
2. Go into survival mode to let it kill you...
3. When you die Leave the server.
4. ????
5. Profit, your console is spammed with NullPointerExceptions.

### Nukkit Version and Client Version

* Nukkit Version: 1.0.6 PE support: 1.2.11 (201)
* Client: Android

#### Config.yml
Defaut.
```

entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: "exampleworld"

max-spawns:
  bat: 0
  blaze: 0
  chicken: 1
  cow: 1
  creeper: 0
  enderman: 0
  ghast: 0
  husk: 0
  horse: 0
  mooshroom: 0
  ocelot: 0
  pig: 1
  polarbear: 1
  rabbit: 1
  stray: 0 
  sheep: 1
  skeleton: 0
  spider: 0
  wolf: 0
  zombie: 0

```
### Crashdump, Backtrace or Other Files
```
[CRITICAL] Could not tick level "world": java.lang.NullPointerException
[ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.walking.Zombie.attackEntity(Zombie.java:125)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:169)
	at cn.nukkit.level.Level.doTick(Level.java:752)
	at cn.nukkit.Server.checkTickUpdates(Server.java:997)
	at cn.nukkit.Server.tick(Server.java:1083)
	at cn.nukkit.Server.tickProcessor(Server.java:846)
	at cn.nukkit.Server.start(Server.java:823)
	at cn.nukkit.Server.<init>(Server.java:506)
	at cn.nukkit.Nukkit.main(Nukkit.java:102)

```

**Comment by PetteriM1** [comment]
@zzz1999 This is due to your path finder

**Comment by zzz1999** [comment]
I dont have time recently...

**Comment by Marfjeh** [comment]
So this isn't getting fixed?

**Comment by PetteriM1** [comment]
@Marfjeh This should be fixed

**Comment by Marfjeh** [comment]
Yeah, I just realized I didn't saw the commit. thanks!

**Comment by zzz1999** [comment]
I forget comment sth...

**Comment by zzz1999** [comment]
This commit maybe fix the question that monsters walking wrong on slabs.
