### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/mob-plugin#8]
How should be worlds listed at worlds-spawn-disabled in config?

**Comment by augesrob** [comment]
I believe  adding the world's name below should do it i could be wrong

**Comment by PetteriM1** [comment]
I don't get it work...
![image](https://user-images.githubusercontent.com/26197131/33523962-1419cc50-d81c-11e7-8855-34a26e9cbad6.JPG)
And creepers break bedrock???

**Comment by augesrob** [comment]
I disabled creepers on my server. Until I can find a protection plugin for spawn.
